dl_core.lo: /home/dl_core/dl_core.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/dl_core $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/dl_core/dl_core.c -o dl_core.lo 
$(phplibdir)/dl_core.la: ./dl_core.la
	$(LIBTOOL) --mode=install cp ./dl_core.la $(phplibdir)

./dl_core.la: $(shared_objects_dl_core) $(DL_CORE_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_dl_core) $(DL_CORE_SHARED_LIBADD)

